version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    cooldown:
      default-days: 2
    groups:
      github-actions-minor-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    cooldown:
      default-days: 5
    groups:
      npm-minor-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
